var annotated_dup =
[
    [ "mui", "namespacemui.html", [
      [ "detail", "namespacemui_1_1detail.html", [
        [ "uint", "structmui_1_1detail_1_1uint.html", null ],
        [ "uint< 1 >", "structmui_1_1detail_1_1uint_3_011_01_4.html", "structmui_1_1detail_1_1uint_3_011_01_4" ],
        [ "uint< 2 >", "structmui_1_1detail_1_1uint_3_012_01_4.html", "structmui_1_1detail_1_1uint_3_012_01_4" ],
        [ "uint< 4 >", "structmui_1_1detail_1_1uint_3_014_01_4.html", "structmui_1_1detail_1_1uint_3_014_01_4" ],
        [ "uint< 8 >", "structmui_1_1detail_1_1uint_3_018_01_4.html", "structmui_1_1detail_1_1uint_3_018_01_4" ],
        [ "endian_converter", "structmui_1_1detail_1_1endian__converter.html", "structmui_1_1detail_1_1endian__converter" ]
      ] ],
      [ "dim", "namespacemui_1_1dim.html", [
        [ "dim", "structmui_1_1dim_1_1dim.html", "structmui_1_1dim_1_1dim" ]
      ] ],
      [ "geometry", "namespacemui_1_1geometry.html", [
        [ "shape", "classmui_1_1geometry_1_1shape.html", "classmui_1_1geometry_1_1shape" ],
        [ "any_shape", "classmui_1_1geometry_1_1any__shape.html", "classmui_1_1geometry_1_1any__shape" ],
        [ "box", "classmui_1_1geometry_1_1box.html", "classmui_1_1geometry_1_1box" ],
        [ "point", "classmui_1_1geometry_1_1point.html", "classmui_1_1geometry_1_1point" ],
        [ "sphere", "classmui_1_1geometry_1_1sphere.html", "classmui_1_1geometry_1_1sphere" ],
        [ "or_set", "classmui_1_1geometry_1_1or__set.html", "classmui_1_1geometry_1_1or__set" ]
      ] ],
      [ "linalg", "namespacemui_1_1linalg.html", [
        [ "sparse_matrix", "classmui_1_1linalg_1_1sparse__matrix.html", "classmui_1_1linalg_1_1sparse__matrix" ],
        [ "preconditioner", "classmui_1_1linalg_1_1preconditioner.html", "classmui_1_1linalg_1_1preconditioner" ],
        [ "incomplete_lu_preconditioner", "classmui_1_1linalg_1_1incomplete__lu__preconditioner.html", "classmui_1_1linalg_1_1incomplete__lu__preconditioner" ],
        [ "incomplete_cholesky_preconditioner", "classmui_1_1linalg_1_1incomplete__cholesky__preconditioner.html", "classmui_1_1linalg_1_1incomplete__cholesky__preconditioner" ],
        [ "symmetric_successive_over_relaxation_preconditioner", "classmui_1_1linalg_1_1symmetric__successive__over__relaxation__preconditioner.html", "classmui_1_1linalg_1_1symmetric__successive__over__relaxation__preconditioner" ],
        [ "diagonal_preconditioner", "classmui_1_1linalg_1_1diagonal__preconditioner.html", "classmui_1_1linalg_1_1diagonal__preconditioner" ],
        [ "solver", "classmui_1_1linalg_1_1solver.html", "classmui_1_1linalg_1_1solver" ],
        [ "conjugate_gradient_1d", "classmui_1_1linalg_1_1conjugate__gradient__1d.html", "classmui_1_1linalg_1_1conjugate__gradient__1d" ],
        [ "conjugate_gradient", "classmui_1_1linalg_1_1conjugate__gradient.html", "classmui_1_1linalg_1_1conjugate__gradient" ],
        [ "biconjugate_gradient_stabilized_1d", "classmui_1_1linalg_1_1biconjugate__gradient__stabilized__1d.html", "classmui_1_1linalg_1_1biconjugate__gradient__stabilized__1d" ],
        [ "biconjugate_gradient_stabilized", "classmui_1_1linalg_1_1biconjugate__gradient__stabilized.html", "classmui_1_1linalg_1_1biconjugate__gradient__stabilized" ],
        [ "gaussian_elimination_1d", "classmui_1_1linalg_1_1gaussian__elimination__1d.html", "classmui_1_1linalg_1_1gaussian__elimination__1d" ],
        [ "gaussian_elimination", "classmui_1_1linalg_1_1gaussian__elimination.html", "classmui_1_1linalg_1_1gaussian__elimination" ]
      ] ],
      [ "communicator", "classmui_1_1communicator.html", "classmui_1_1communicator" ],
      [ "comm_factory", "structmui_1_1comm__factory.html", null ],
      [ "comm_mpi", "classmui_1_1comm__mpi.html", "classmui_1_1comm__mpi" ],
      [ "comm_mpi_smart", "classmui_1_1comm__mpi__smart.html", "classmui_1_1comm__mpi__smart" ],
      [ "smalluint", "structmui_1_1smalluint.html", "structmui_1_1smalluint" ],
      [ "mutex_timeout", "structmui_1_1mutex__timeout.html", "structmui_1_1mutex__timeout" ],
      [ "unique_fd_", "classmui_1_1unique__fd__.html", "classmui_1_1unique__fd__" ],
      [ "poll_scheduler", "classmui_1_1poll__scheduler.html", "classmui_1_1poll__scheduler" ],
      [ "read_que", "classmui_1_1read__que.html", "classmui_1_1read__que" ],
      [ "write_que", "classmui_1_1write__que.html", "classmui_1_1write__que" ],
      [ "comm_fd", "classmui_1_1comm__fd.html", "classmui_1_1comm__fd" ],
      [ "dispatcher", "structmui_1_1dispatcher.html", "structmui_1_1dispatcher" ],
      [ "singleton", "classmui_1_1singleton.html", null ],
      [ "uri", "classmui_1_1uri.html", "classmui_1_1uri" ],
      [ "message", "structmui_1_1message.html", "structmui_1_1message" ],
      [ "reader_variables", "structmui_1_1reader__variables.html", "structmui_1_1reader__variables" ],
      [ "type_list", "structmui_1_1type__list.html", null ],
      [ "one_dim", "structmui_1_1one__dim.html", "structmui_1_1one__dim" ],
      [ "two_dim", "structmui_1_1two__dim.html", "structmui_1_1two__dim" ],
      [ "three_dim", "structmui_1_1three__dim.html", "structmui_1_1three__dim" ],
      [ "default_config", "structmui_1_1default__config.html", null ],
      [ "endian_traits", "structmui_1_1endian__traits.html", null ],
      [ "endian_traits< T, typename std::enable_if< std::is_integral< T >::value >::type >", "structmui_1_1endian__traits_3_01_t_00_01typename_01std_1_1enable__if_3_01std_1_1is__integral_3_017f2a9fc75456eff64bb43276e6e0ef4.html", null ],
      [ "endian_traits< T, typename std::enable_if< std::is_floating_point< T >::value >::type >", "structmui_1_1endian__traits_3_01_t_00_01typename_01std_1_1enable__if_3_01std_1_1is__floating__po2204fe17b69811056c26bb26c4197e1a.html", null ],
      [ "exception_segv", "structmui_1_1exception__segv.html", "structmui_1_1exception__segv" ],
      [ "exception_abort", "structmui_1_1exception__abort.html", "structmui_1_1exception__abort" ],
      [ "exception_throw", "structmui_1_1exception__throw.html", "structmui_1_1exception__throw" ],
      [ "triple", "structmui_1_1triple.html", "structmui_1_1triple" ],
      [ "same_type", "structmui_1_1same__type.html", null ],
      [ "same_type< T, T >", "structmui_1_1same__type_3_01_t_00_01_t_01_4.html", null ],
      [ "vexpr", "structmui_1_1vexpr.html", "structmui_1_1vexpr" ],
      [ "point", "structmui_1_1point.html", "structmui_1_1point" ],
      [ "vexpr_add", "structmui_1_1vexpr__add.html", "structmui_1_1vexpr__add" ],
      [ "vexpr_sub", "structmui_1_1vexpr__sub.html", "structmui_1_1vexpr__sub" ],
      [ "vexpr_neg", "structmui_1_1vexpr__neg.html", "structmui_1_1vexpr__neg" ],
      [ "vexpr_mul", "structmui_1_1vexpr__mul.html", "structmui_1_1vexpr__mul" ],
      [ "vexpr_scale", "structmui_1_1vexpr__scale.html", "structmui_1_1vexpr__scale" ],
      [ "vexpr_div", "structmui_1_1vexpr__div.html", "structmui_1_1vexpr__div" ],
      [ "vexpr_rscale", "structmui_1_1vexpr__rscale.html", "structmui_1_1vexpr__rscale" ],
      [ "vexpr_rcp", "structmui_1_1vexpr__rcp.html", "structmui_1_1vexpr__rcp" ],
      [ "vexpr_scale_rcp", "structmui_1_1vexpr__scale__rcp.html", "structmui_1_1vexpr__scale__rcp" ],
      [ "vexpr_apply1", "structmui_1_1vexpr__apply1.html", "structmui_1_1vexpr__apply1" ],
      [ "vexpr_apply2", "structmui_1_1vexpr__apply2.html", "structmui_1_1vexpr__apply2" ],
      [ "span", "classmui_1_1span.html", "classmui_1_1span" ],
      [ "algo_aitken", "classmui_1_1algo__aitken.html", "classmui_1_1algo__aitken" ],
      [ "algo_fixed_relaxation", "classmui_1_1algo__fixed__relaxation.html", "classmui_1_1algo__fixed__relaxation" ],
      [ "algo_null", "classmui_1_1algo__null.html", "classmui_1_1algo__null" ],
      [ "sampler_exact", "classmui_1_1sampler__exact.html", "classmui_1_1sampler__exact" ],
      [ "sampler_gauss", "classmui_1_1sampler__gauss.html", "classmui_1_1sampler__gauss" ],
      [ "sampler_moving_average", "classmui_1_1sampler__moving__average.html", "classmui_1_1sampler__moving__average" ],
      [ "sampler_nearest_neighbor", "classmui_1_1sampler__nearest__neighbor.html", "classmui_1_1sampler__nearest__neighbor" ],
      [ "sampler_null", "classmui_1_1sampler__null.html", "classmui_1_1sampler__null" ],
      [ "sampler_pseudo_n2_linear", "classmui_1_1sampler__pseudo__n2__linear.html", "classmui_1_1sampler__pseudo__n2__linear" ],
      [ "sampler_pseudo_nearest_neighbor", "classmui_1_1sampler__pseudo__nearest__neighbor.html", "classmui_1_1sampler__pseudo__nearest__neighbor" ],
      [ "sampler_rbf", "classmui_1_1sampler__rbf.html", "classmui_1_1sampler__rbf" ],
      [ "sampler_shepard_quintic", "classmui_1_1sampler__shepard__quintic.html", "classmui_1_1sampler__shepard__quintic" ],
      [ "sampler_sph_quintic", "classmui_1_1sampler__sph__quintic.html", "classmui_1_1sampler__sph__quintic" ],
      [ "sampler_sum_quintic", "classmui_1_1sampler__sum__quintic.html", "classmui_1_1sampler__sum__quintic" ],
      [ "temporal_sampler_exact", "classmui_1_1temporal__sampler__exact.html", "classmui_1_1temporal__sampler__exact" ],
      [ "temporal_sampler_gauss", "classmui_1_1temporal__sampler__gauss.html", "classmui_1_1temporal__sampler__gauss" ],
      [ "temporal_sampler_mean", "classmui_1_1temporal__sampler__mean.html", "classmui_1_1temporal__sampler__mean" ],
      [ "temporal_sampler_null", "classmui_1_1temporal__sampler__null.html", "classmui_1_1temporal__sampler__null" ],
      [ "temporal_sampler_sum", "classmui_1_1temporal__sampler__sum.html", "classmui_1_1temporal__sampler__sum" ],
      [ "bin_range", "structmui_1_1bin__range.html", "structmui_1_1bin__range" ],
      [ "bin_iterator", "structmui_1_1bin__iterator.html", "structmui_1_1bin__iterator" ],
      [ "bin_t", "structmui_1_1bin__t.html", "structmui_1_1bin__t" ],
      [ "bad_storage_id", "structmui_1_1bad__storage__id.html", "structmui_1_1bad__storage__id" ],
      [ "bad_storage_cast", "structmui_1_1bad__storage__cast.html", "structmui_1_1bad__storage__cast" ],
      [ "storage", "structmui_1_1storage.html", "structmui_1_1storage" ],
      [ "spatial_storage", "classmui_1_1spatial__storage.html", "classmui_1_1spatial__storage" ],
      [ "istream", "classmui_1_1istream.html", "classmui_1_1istream" ],
      [ "ostream", "classmui_1_1ostream.html", "classmui_1_1ostream" ],
      [ "iostream", "classmui_1_1iostream.html", "classmui_1_1iostream" ],
      [ "container_stream", "classmui_1_1container__stream.html", "classmui_1_1container__stream" ],
      [ "iitr_stream", "classmui_1_1iitr__stream.html", "classmui_1_1iitr__stream" ],
      [ "oitr_stream", "classmui_1_1oitr__stream.html", "classmui_1_1oitr__stream" ],
      [ "ocount_stream", "classmui_1_1ocount__stream.html", "classmui_1_1ocount__stream" ],
      [ "index_sequence", "structmui_1_1index__sequence.html", "structmui_1_1index__sequence" ],
      [ "make_index_sequence", "structmui_1_1make__index__sequence.html", "structmui_1_1make__index__sequence" ],
      [ "make_index_sequence< 0 >", "structmui_1_1make__index__sequence_3_010_01_4.html", "structmui_1_1make__index__sequence_3_010_01_4" ],
      [ "index_iterator", "structmui_1_1index__iterator.html", "structmui_1_1index__iterator" ],
      [ "virtual_container", "classmui_1_1virtual__container.html", "classmui_1_1virtual__container" ],
      [ "uniface", "classmui_1_1uniface.html", "classmui_1_1uniface" ]
    ] ]
];